-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 20:33:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejemplo1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo1` ;

-- -----------------------------------------------------
-- Schema ejemplo1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo1` DEFAULT CHARACTER SET utf8 ;
USE `ejemplo1` ;

-- -----------------------------------------------------
-- Table `ejemplo1`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejemplo1`.`departamentos` (
  `dept_no` INT NOT NULL,
  `dnombre` VARCHAR(25) NULL,
  `loc` VARCHAR(15) NULL,
  PRIMARY KEY (`dept_no`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `dept_no_UNIQUE` ON `ejemplo1`.`departamentos` (`dept_no` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ejemplo1`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejemplo1`.`empleados` (
  `emp_no` INT NOT NULL,
  `apellidos` VARCHAR(25) NULL,
  `oficio` VARCHAR(25) NULL,
  `dir` INT NULL,
  `fecha_alta` DATE NULL,
  `salario` FLOAT NULL,
  `comision` FLOAT NULL,
  `dept_no` INT NULL,
  PRIMARY KEY (`emp_no`),
  CONSTRAINT `fk_empleados_departamentos`
    FOREIGN KEY (`dept_no`)
    REFERENCES `ejemplo1`.`departamentos` (`dept_no`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleados_empleados1`
    FOREIGN KEY (`dir`)
    REFERENCES `ejemplo1`.`empleados` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `emp_no_UNIQUE` ON `ejemplo1`.`empleados` (`emp_no` ASC) VISIBLE;

CREATE INDEX `fk_empleados_departamentos_idx` ON `ejemplo1`.`empleados` (`dept_no` ASC) VISIBLE;

CREATE INDEX `fk_empleados_empleados1_idx` ON `ejemplo1`.`empleados` (`dir` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
